---
- name: Deploy Dockerized Nginx Web Application
  hosts: remote_server
  become: true
  
  tasks:
    - name: Copy docker-compose.yml file
      copy:
        src: docker-compose.yml
        dest: /path/to/remote/docker-compose.yml
    
    - name: Copy Nginx configuration template
      copy:
        src: nginx.conf.j2
        dest: /path/to/remote/nginx.conf.j2
    
    - name: Install Docker and Docker Compose
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
    
    - name: Start Docker service
      service:
        name: docker
        state: started
    
    - name: Build and start the Docker containers
      command: docker-compose up -d
      args:
        chdir: /path/to/remote/
    
    - name: Generate Nginx configuration file from template
      template:
        src: /path/to/remote/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: Restart Nginx
    
  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
